### ISSUE TITLE
Add a custom-derive for `Actor`

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#127]
Although it doesn't require much boilerplate at the moment, I think it would be a nice addition to add a `derive(Actor)` macro that generates a default `Actor` implementation with `Stop = ()`.

**Comment by Restioson** [comment]
I agree - would this be possible to have in an ext crate or not?

**Comment by thomaseizinger** [comment]
I was thinking of having something like `xtra_macros` at some point but re-export it from `xtra` so it can be used as:

```rust
#[derive(xtra::Actor)]
struct MyActor;
```

**Comment by Restioson** [comment]
Sounds like a good solution!

**Comment by thomaseizinger** [comment]
For the future developer that works on this:

- Use `trybuild` to test the macro
- Make sure to handle generics on the actor struct correctly
- Consider using `darling`
