### ISSUE TITLE
Is it worth having `SendingNamed` and `SendingErased`?

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#132]
Currently, we have two ways of constructing a `SendFuture`: One that retains the actor type and one that boxes the inner future up. The latter is required for `MessageChannel` to work.

As a consequence, we need to have another `SendFuture` exposed by the channel implementation that we can nest in the upper-most `SendFuture`. This indirection is a bit annoying and makes things harder to understand. It also makes things like #120 harder to implement. I think that this particular instrumentation feature would be easier to build if there were less indirection.

Would it be worth it to always pay the cost of an additional allocation and inline the inner `SendFuture` in the outer one in favor of less indirection and features like #120 being easier to implement? I also have a feeling that most of the other instrumentation would be easier if we had less indirection here.

**Comment by Restioson** [comment]
I'm not quite sure I follow, given that to me unconditionally boxing the future leads to more indirection and not less?

**Comment by thomaseizinger** [comment]
I was hoping to avoid some of the indirection by inlining the `tx::SendFuture` completely and implementing it as a closure passed to `poll_fn` or something like that. The constructor of `SendFuture` would be a bit bigger but a lot of the logic would be in one place.

Something like:

```rust
pub(crate) fn sending_erased<M, A, Rc>(message: M, sender: inbox::Sender<A, Rc>) -> Self
        where
            Rc: TxRefCounter,
            A: Handler<M, Return=R>,
            M: Send + 'static,
            R: Send + 'static,
    {
        let (envelope, rx) = ReturningEnvelope::<A, M, R>::new(message);
        let msg = PriorityMessageToOne::new(0, Box::new(envelope));

        Self {
            inner: SendFutureInner::Sending(ActorErasedSending {
                future: Box::pin(async move {
                    match sender.inner.try_send(SentMessage::ToOneActor(msg)) {
                        Ok(()) => Ok(()),
                        Err(TrySendFail::Disconnected) => Err(Error::Disconnected),
                        Err(TrySendFail::Full(waiting)) => waiting.lock().await,
                    }
                }),
                rx: Some(rx),
            }),
            phantom: PhantomData,
        }
    }
```

This in particular is not going to work because we would be holding the `lock` across the await point but I think it might be possible to redesign to have the `WaitingSender` have the lock internally?

**Comment by Restioson** [comment]
Hmm... If possible I'd like to avoid the heap allocation, since I'd expect this to be worse for cache locality in most cases, as well as taking extra time to allocate the on send.

**Comment by thomaseizinger** [comment]
Okay, let's see how far we can get without the extra allocation.
