### ISSUE TITLE
Actor with a CPU-bound task

### ISSUE THREAD

**Issue by bobdebuildr** [Restioson/xtra#183]
I found a discussion about handling a CPU-bound task in issue #17, however it seems to be based on a previous version of `xtra`. Are the recommendations there still current?

My use case involves a function that I know is CPU-bound, and would block my executor (I'm using tokio).
Another option I'm thinking about is having the `Actor` start a `ScopedTask` in its `started` function that basically does something like this:

```rust
use xtra::{prelude::*, scoped};

pub struct MyActor {
    pub task: Option<tokio::task::JoinHandle<Option<()>>>,
}

fn blocking_fct() {
    println!("background task: sleeping");
    std::thread::sleep(std::time::Duration::from_secs(5));
    println!("background task: done sleeping");
}

#[async_trait]
impl Actor for MyActor {
    type Stop = ();

    async fn started(&mut self, ctx: &mut Context<Self>) {
        // `spawn_blocking` gives an awaitable handle while making sure
        // it doesn't interfere with any tokio async tasks
        let handle = tokio::task::spawn_blocking(blocking_fct);
        // `scoped` ensures that the handle gets killed if the actor exits earlier
        let han = tokio::spawn(scoped(&ctx.address().unwrap(), async {
            handle.await.unwrap();
        }));
        self.task = Some(han);
        println!("spawned background task");
    }

    async fn stopped(self) {
        if let Some(handle) = self.task {
            handle.abort();
            handle.await.unwrap();
        }
    }
}
```

Is this a "good" solution, or do you have a better recommendation for this scenario? Is my code comment about how `scoped(..)` works correct?

**Comment by bobdebuildr** [comment]
Yes, it's CPU bound: basically it does some fancy parsing that takes around 2-5 seconds of CPU time. I would like to keep the latency as low as possible and not risk waiting that long.

I'll take a look at the second option, it seems to be a bit simpler.

In this case, how would I go about running multiple instances of the actor in parallel? Would I implement a `ManagerActor` that has a `Vec<Address<MyActor>>` and does a round-robin load distribution between multiple instances? Or is there a simpler way to associate multiple instances with one address to do this transparently?

**Comment by Restioson** [comment]
> In this case, how would I go about running multiple instances of the actor in parallel? Would I implement a ManagerActor that has a Vec<Address<MyActor>> and does a round-robin load distribution between multiple instances? Or is there a simpler way to associate multiple instances with one address to do this transparently?

Xtra has this built in :) You can clone the `Context` and call `run` on it again. See the [message stealing actors](https://github.com/Restioson/xtra/blob/master/examples/message_stealing_multiple_actors.rs#L46) example.

**Comment by bobdebuildr** [comment]
Ok great, thanks for the help. I'll play around with it a bit and let you know how it works out.

**Comment by thomaseizinger** [comment]
With a CPU-bound task, does it make sense to have multiple actors running on the same `Context`?

In case the thread is 100% busy with one actor handling a message, what is the point of a 2nd or 3rd actor?

I think that may be worth benchmarking before you spawn N of those actors on the _same_ thread. You can of course spawn a new thread for each `run` future.

**Comment by thomaseizinger** [comment]
It may be worth to utilize tokio's `spawn_blocking` here to spawn those `run` futures and have tokio do the thread management.

**Comment by Restioson** [comment]
> In case the thread is 100% busy with one actor handling a message, what is the point of a 2nd or 3rd actor?

If you have multiple messages, coming in, then a 2nd actor can work on that. If it's just one message at a time which takes 100% for however long, then it wouldn't be worth it, I agree.

> I think that may be worth benchmarking before you spawn N of those actors on the same thread. You can of course spawn a new thread for each run future.

Yea, this is what I meant.

> It may be worth to utilize tokio's spawn_blocking here to spawn those run futures and have tokio do the thread management.

I asked about this on the tokio discord, and it was recommended against, given that the actor will last for a long time, whereas spawn_blocking tasks should be short and for one piece of work.

**Comment by thomaseizinger** [comment]
> > It may be worth to utilize tokio's spawn_blocking here to spawn those run futures and have tokio do the thread management.
> 
> I asked about this on the tokio discord, and it was recommended against, given that the actor will last for a long time, whereas spawn_blocking tasks should be short and for one piece of work. So, you end up using up one of the blocking threads from the pool for a significant amount of time. In that case, it is better to just spawn your own thread. This is for the 1 thread per actor case.

That is interesting, thanks for sharing :)
