### ISSUE TITLE
wait for actor to finish processing entire mailbox

### ISSUE THREAD

**Issue by bobdebuildr** [Restioson/xtra#184]
I'm having trouble finding a way to wait for my actors to finish their processing before exiting my program.

I have some data that should be processed, being passed around between different actors while doing so. What I want to guarantee is that my program does not stop before the last actor(s) in the chain finish their processing- i.e. that all handlers are done and all mailboxes are completely empty.

How can I do this? One way to do it manually would be to repeatedly call a function that gets the number of messages in the mailbox, but I wasn't able to find anything like that. And in that case, I would miss messages that are send by a busy handler after running the check.

**Comment by Restioson** [comment]
Ideally, I would structure such an example so that all the actors naturally finish when their work is done. With this, and the use of weak addresses, the final actor would have no strong references to it, so it would stop. Then, you can just await the actor future and return the relevant data from `Stopped`. Otherwise, it could stop itself when done, presuming it has some level of introspection as to when it is done. If it does not, I would try and design it so that when there is no more input, then there are no more strong addresses to the actor, so the actor will naturally stop. That is the ideal use of the xtra actor lifecycle, imo.

Let me know if this doesn't work for any reason (clarification would be appreciated!)

**Comment by Restioson** [comment]
> Ok, I think I understand the idea, and it sounds exactly like what I would want. Am I correct in assuming that by "await the actor future" you're referring to the join function?

I am referring to the actor itself's future. See [this example](https://github.com/Restioson/xtra/blob/master/examples/manual_actor_impl.rs#L50) for more. `join` simply returns when the actor itself stops, so it will return at the same time but not with the value of `Stop`.

> The only thing that's not working is to get something when it's stopped- it doesn't seem to be possible when spawning actors like this (it requires Stop = ()). I that correct or am I missing something?

This is an artificial limit to prevent users from throwing away the `Stop` value by spawning an actor. You can use `context.run(actor)` in this case instead.

**Comment by bobdebuildr** [comment]
Ah I see, thank you very much for the help! The linked example makes it very clear.

**Comment by Restioson** [comment]
Glad I could be of help!

**Comment by bobdebuildr** [comment]
I have one more question about how actors stop:
When there are no more strong Addresses left, does the actor stop immediately, or does it first finish processing all messages in its mailbox? I wasn't able to find anything about this in the documentation.
Also, I assume that when the actor is busy processing the last message in its mailbox, `address.len()` will be zero, correct?

**Comment by Restioson** [comment]
>  When there are no more strong Addresses left, does the actor stop immediately, or does it first finish processing all messages in its mailbox? I wasn't able to find anything about this in the documentation.

It will finish processing all messages. This should probably be mentioned explicitly in the docs but it isn't, like you noted.

>  Also, I assume that when the actor is busy processing the last message in its mailbox, address.len() will be zero, correct?

Yes.

**Comment by bobdebuildr** [comment]
Ok great, thanks for clearing that up. I'm collecting some small suggestions for the documentation and will make a pull request when it's ready.

There's some more unexpected behavior I came across when trying to make sure that I don't have any more strong addresses to an actor left.
In my main function, I pass around a strong address (by cloning) to various actors, which will be dropped when the actors finish. I then want to overwrite the remaining variable in the main function by a weak address, using: `let adr = adr.downgrade();`. The `adr` at the left is weak, on the right-hand side it is strong. In my understanding, this should drop the strong address.

However, that doesn't seem to be the case. The statement above is not equivalent to the following:

```rust
let adr = {
    let a = adr.downgrade();
    drop(adr);
    a
};
```

What am I missing here?

**Comment by Restioson** [comment]
This doesn't drop the strong address as `Address::downgrade` takes `&self`, so it is not consumed. You could also do
```rust
let weak = addr.downgrade();
drop(addr);
```
