### ISSUE TITLE
`as_either` for `MessageChannel`?

### ISSUE THREAD

**Issue by bobdebuildr** [Restioson/xtra#188]
I would like to store various `MessageChannel<M, R, Rc>` in a `Vec<MessageChannel<M, R, Either>>`, where `Rc` could vary. It would be nice to have an `as_either()` function on `MessageChannel` similar to the one for `Address`.

Is there some deeper reason why this isn't possible or shouldn't be done?

**Comment by bobdebuildr** [comment]
I managed to add this function- if you're interested I can open a pull request.

**Comment by Restioson** [comment]
Good catch! This was probably missed in #102. Feel free to open a PR, I'd appreciate that :)

**Comment by thomaseizinger** [comment]
Resolved in #192.
