### ISSUE TITLE
Add Clone impl to MessageChannel and WeakMessageChannel

### ISSUE THREAD

**Issue by geigerzaehler** [Restioson/xtra#19]
It would be great if `MessageChannel` and `WeakMessageChannel` would implement `Clone` like `Address`. I have a [patch for this](https://github.com/geigerzaehler/xtra/commit/467f22a6efb7b02842a0279dad8fb9c1cd071950) based on `v0.4.2` of this crate since `v0.5` still seems to be under development.

**Comment by Restioson** [comment]
In 0.5, I'm of a mind to make MessageChannel and WeakMessageChannel into traits, where you manually construct the trait object yourself - this is more flexible as one can avoid boxing in the case of `&dyn MessageChannel<M>`, and it was pretty much what was done under the hood anyway. I will be sure to add a `clone` function to these traits then!

IBy the way, if moving from implicit boxed trait objects (the old solution) to explicit boxed trait objects (`Box<dyn MessageChannel<M>>`) would break one of your use-cases, any feedback greatly is appreciated!

**Comment by geigerzaehler** [comment]
> By the way, if moving from implicit boxed trait objects (the old solution) to explicit boxed trait objects (`Box<dyn MessageChannel<M>>`) would break one of your use-cases, any feedback greatly is appreciated!

The new approach will work provided there is an appropriate method available on `MessageChannel`. What I need is something like this.
```rust
fn spawn_multiple_senders(message_channel: &dyn MessageChannel<MyMessage>) {
  for _ in 0..5 {
    spawn_sender(message_channel.dup())
  }
}
```
Note that passing `message_channel` by reference does not work because the life time would need to be static.

**Comment by Restioson** [comment]
Ok, I will provide a `clone` or `dup` method like this which returns `Box<dyn MessageChannel<M>>` in 0.5.

**Comment by Restioson** [comment]
This is complete in 0.5.0-beta.5, which will likely become 0.5.0 pending the discovery of any issues.
