### ISSUE TITLE
wasm_bindgen::JsValue within Actor?

### ISSUE THREAD

**Issue by dimitri-lenkov** [Restioson/xtra#195]
Hi there.

I've been evaluating actor libraries with wasm_bindgen support (there aren't a lot to be honest!). I like the simplicity of this library and it seems to work well within a browser context; however, it does not support [`JsValue`'s](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/struct.JsValue.html) within Actors.

This can be demonstrated by adding a simple `JsValue` field to the Echor struct in `xtra/examples/basic_wasm_bindgen/src/lib.rs`:

![2022-11-15_JsValue](https://user-images.githubusercontent.com/83975180/202041271-c7b0f7a0-d8f7-4e4f-b161-e9124f16441c.png)

- - -

<details><summary><strong>CLICK HERE</strong> to expand the full source of `lib.rs` that has the changes in the diff above.</summary>

```rust
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsValue;
use xtra::prelude::*;

#[derive(xtra::Actor)]
struct Echoer {
    some_js_value: JsValue // JsValue is !Send
}

struct Echo(String);

#[async_trait]
impl Handler<Echo> for Echoer {
    type Return = String;

    async fn handle(&mut self, echo: Echo, _ctx: &mut Context<Self>) -> String {
        echo.0
    }
}

#[wasm_bindgen]
pub async fn start() -> Result<(), JsValue> {
    let addr = xtra::spawn_wasm_bindgen(Echoer {
        some_js_value: JsValue::from_str("デク")
    }, Mailbox::unbounded());
    let response = addr
        .send(Echo("hello world".to_string()))
        .await
        .expect("Echoer should not be dropped");

    assert_eq!(response, "hello world");

    Ok(())
}

```
</details>

- - -

Running this source leads to the following error:

```text
[~/git/tmp/xtra/xtra/examples/basic_wasm_bindgen]$ nix-shell -p rustup wasm-pack geckodriver pkgconfig openssl
[nix-shell:~/git/tmp/xtra/xtra/examples/basic_wasm_bindgen]$ ./test.sh 
[INFO]: Checking for the Wasm target...
   Compiling basic-wasm-bindgen v0.1.0 (/home/jay/git/tmp/xtra/xtra/examples/basic_wasm_bindgen)
error[E0277]: `*mut u8` cannot be sent between threads safely
   --> xtra/examples/basic_wasm_bindgen/src/lib.rs:5:10
    |
5   | #[derive(xtra::Actor)]
    |          ^^^^^^^^^^^ `*mut u8` cannot be sent between threads safely
    |
    = help: within `Echoer`, the trait `Send` is not implemented for `*mut u8`
    = note: required because it appears within the type `PhantomData<*mut u8>`
    = note: required because it appears within the type `JsValue`
note: required because it appears within the type `Echoer`
   --> xtra/examples/basic_wasm_bindgen/src/lib.rs:6:8
    |
6   | struct Echoer {
    |        ^^^^^^
note: required by a bound in `Actor`
   --> /home/jay/git/tmp/xtra/xtra/src/lib.rs:182:28
    |
182 | pub trait Actor: 'static + Send + Sized {
    |                            ^^^^ required by this bound in `Actor`
    = note: this error originates in the derive macro `xtra::Actor` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `*mut u8` cannot be sent between threads safely
   --> xtra/examples/basic_wasm_bindgen/src/lib.rs:13:6
    |
13  | impl Handler<Echo> for Echoer {
    |      ^^^^^^^^^^^^^ `*mut u8` cannot be sent between threads safely
    |
    = help: within `Echoer`, the trait `Send` is not implemented for `*mut u8`
    = note: required because it appears within the type `PhantomData<*mut u8>`
    = note: required because it appears within the type `JsValue`
note: required because it appears within the type `Echoer`
   --> xtra/examples/basic_wasm_bindgen/src/lib.rs:6:8
    |
6   | struct Echoer {
    |        ^^^^^^
note: required by a bound in `xtra::Handler`
   --> /home/jay/git/tmp/xtra/xtra/src/lib.rs:118:23
    |
118 | pub trait Handler<M>: Actor {
    |                       ^^^^^ required by this bound in `xtra::Handler`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `basic-wasm-bindgen` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `basic-wasm-bindgen` due to 2 previous errors
Error: Compilation of your program failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--tests" "--target" "wasm32-unknown-unknown"
```

- - -

Is there a quick-and-dirty hack I can use to get around this? My current solution loosely follows this guide (but with `wasm_bindgen_futeres::spawn_local`):

https://ryhl.io/blog/actors-with-tokio/

And it works, but, it's missing a lot of the nice features that `xtra` supports.

**Comment by dimitri-lenkov** [comment]
Found some thoughts from @Restioson on this exact issue:

https://github.com/Restioson/xtra/issues/7

If you can give me some pointers in the current development branch on where to start tackling this problem I'm happy to poke and prod around even-if it requires duplication of code. I'm working on a code base that targets two WebRTC implementations: [webrtc-rs](https://github.com/webrtc-rs/webrtc) and the WebIDL bindings to WebRTC that [web_sys](https://docs.rs/web-sys/latest/web_sys/struct.RtcDataChannel.html) provides (but web_sys marks `JsValue`'s as `!Send`).

I've ported some of my crude hand-rolled actors to `xtra` and like what I see (it worked *perfectly* with `webrtc-rs`), but when I tested the browser peers (using the `web_sys` bindings to WebRTC) things went all sideways haha.

Sorry for the spam. I really like this library so far ~ :rose:

**Comment by thomaseizinger** [comment]
Annoyingly, we currently have to enforce that the `Actor` is either `Send` or `!Send` because async fns in traits are not yet stable.

As a workaround, we use the `async-trait` proc macro which boxes the future into a trait object. At that point you unfortunately have to make a decision on what traits your type implements (i.e. type inference goes out the window) and this includes `Send`.

Once we have native async functions in traits, I believe we will just be able to have the Rust compiler infer whether the `Actor` is `Send` and this problem should be resolved.

**Comment by dimitri-lenkov** [comment]
@thomaseizinger thank you for the reply. I went down a path last night changing everything to [`#[async_trait(?Send)]`](https://docs.rs/async-trait/latest/async_trait/#non-threadsafe-futures) and removing all [`Send` marker traits](https://doc.rust-lang.org/nomicon/send-and-sync.html) but was met with a wall of errors that I did not understand :crying_cat_face: .

I keep reading that because GAT's are now stable, that async traits are closer to being here. Once they land you bet I'll re-consider this library!

I'm going to borrow some ideas from this crate in the meantime. 

Bye.

**Comment by Restioson** [comment]
Having non-Send actors was endlessly annoying trying to use xtra with GTK, but unfortunately I could not get it to work :( I had some ideas about how to _maybe_ make it work with GATs, though, so I'll keep you posted on that! Still very experimental though. 

One way forward might be to fork and remove the Sync/Send bounds everywhere. This will result in every actor being !Send, which is unacceptable for general use, but for wasm it's completely ok.
