### ISSUE TITLE
Feature Request: relax return type in into sink

### ISSUE THREAD

**Issue by elyase** [Restioson/xtra#197]
it there a reason why [`into_sink`](https://github.com/Restioson/xtra/blob/ca061b4090eaa2a563dbe582ec3b48a018729cf7/xtra/src/address.rs#L241) only supports handlers with `Return = ()`?

**Comment by thomaseizinger** [comment]
Yes because all return values would be lost as `Sink`s don't support returning them.

If you are okay with that, you can easily implement your own. But it would be more type-safe to create a new handler that does error handling etc inside and thus confirms to the interface.

**Comment by elyase** [comment]
makes sense, thanks for clarifying!
