### ISSUE TITLE
Should we still recommend `spaad` in the README?

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#200]
At the moment, the README recommends to try `spaad` in case one wants better ergonomics out of `xtra`.

Personally, I was never a big fan of `spaad` because I've found that it obfuscates too many things. With the upcoming release, the public API of `xtra` changed massively and I believe it is now in a state where it provides great control over what is happening without too much boilerplate. For example, the `split_receiver` functionality is only available on `SendFuture` which would be hidden by something like `spaad`.

Especially once we add https://github.com/Restioson/xtra/issues/111 and `async fn` in traits being hopefully stable soon, the amount of boilerplate is practically zero, i.e. every line of code is intentional and not a "this library is making me write code that I don't want to write".

**Comment by Restioson** [comment]
I am not 100% sure if we should _recommend_ it per se but it might be worth a mention. I also agree. Spaad was always a little bit of an experiment with it and I was not totally satisfied with how it turned out.

**Comment by thomaseizinger** [comment]
Yeah, we should definitely mention it. What irks me is that the current wording suggests that `xtra` is too verbose to use by itself when at least in my opinion, it definitely isn't.

**Comment by Restioson** [comment]
I agree :) I think that macros are a little unergonomic and we should strive to improve xtra's usability outside of other macros like what was done in spaad.
