### ISSUE TITLE
Atomicity of handlers

### ISSUE THREAD

**Issue by zesterer** [Restioson/xtra#204]
Hello.

Given the signature of `Handler::handle`, it seems like the returned future is permitted to borrow from `self`. This is convenient for sure, but I wonder whether it there is a mechanism to allow long-lived handlers to drop references to `self`, reborrowing them later (akin to Actix's admittedly troublesome combinator API)?

This would permit other handlers on the actor can run while the original is waiting on IO. Am I right in thinking that, today, all handlers in `xtra` are effectively equivalent to Actix's `AtomicResponse`?

**Comment by thomaseizinger** [comment]
I am not too familiar with `actix` API but my thoughts on long-running handlers are:

- If you have a long-running task, you should just spawn that into a runtime and send a message back to the actor once finished.
- Be careful to not circumvent back-pressure this way. Spawning tasks is "unbounded" on pretty much all executors I think?
- Tasks are not owned by an actor, meaning they will keep running even if the actor is shut down. Keep that in mind when you spawn tasks from handlers.

For IO, I'd typically spawn 1(!) task that reads from the IO source and immediately delegates to an actor, waiting for the handler to finish before reading the next message.

Does this help?

**Comment by zesterer** [comment]
Thanks, that clarifies things.
