### ISSUE TITLE
0.6 Release

### ISSUE THREAD

**Issue by sinui0** [Restioson/xtra#213]
Hi, just curious when you intend to release 0.6 on `crates.io`. Are you currently holding off in favor of adopting RPITIT/AFIT on stable in a few weeks?

**Comment by thomaseizinger** [comment]
> @thomaseizinger any opinion on waiting for RPITIT or cutting a release now?

I mean, now we are 3 weeks away from RPITIT, might as well wait for that instead of cutting two consecutive releases?

**Comment by Restioson** [comment]
@thomaseizinger: do you think we are ready to cut this after we bump some deps?

**Comment by thomaseizinger** [comment]
Let's just release what we have I'd say :)

We can bump dependencies later!

**Comment by Restioson** [comment]
Fair enough, we may as well. There's never a perfect time. I'll cut one now as it's long overdue
