### ISSUE TITLE
Performance, benchmarks, comparison

### ISSUE THREAD

**Issue by dumblob** [Restioson/xtra#22]
Have you tried any performance tests? Even if it's not the goal of this lib it'd be nice to know what we're looking at :wink:.

**Comment by Restioson** [comment]
(I've transferred this issue to the relevant repository, btw)

**Comment by dumblob** [comment]
Sorry, my bad. I didn't notice `xtra` itself has some tiny benchmarks. It's all I was looking for :wink:. Thanks for the pointer!

**Comment by Restioson** [comment]
No problem! If you have any other benchmarks you'd like to see feel free to open an issue or PR!
