### ISSUE TITLE
The example code in README is outdated

### ISSUE THREAD

**Issue by constlhq** [Restioson/xtra#222]
> `let addr = xtra::spawn_tokio(Printer::default(), None);` 

Type mismatch [E0308] expected `(Address<Printer>, Mailbox<Printer>)`, but found `Option<_>`

**Comment by thomaseizinger** [comment]
Darn, yeah that one is not CI tested. I recommend looking at the actual examples: https://github.com/Restioson/xtra/tree/master/xtra/examples

PRs welcome to fix the README! :)
