### ISSUE TITLE
New beta release

### ISSUE THREAD

**Issue by lelongg** [Restioson/xtra#23]
The last release (0.5.0-beta.5) is broken since smol 1.1, but master works, so would you consider releasing a new one ?

```
   |
28 |         Handle(&'a smol::Executor)
   |                          ^^^^^^^^ expected named lifetime parameter
   |
help: consider using the `'a` lifetime
   |
28 |         Handle(&'a smol::Executor<'a>)
   |                          ^^^^^^^^^^^^
```

**Comment by Restioson** [comment]
I will release one tonight :+1:

**Comment by Restioson** [comment]
Huh, looks like this was actually a breaking change in smol, since originally there was no `'a`:
```rust
error[E0107]: wrong number of lifetime arguments: expected 0, found 1
  --> src/spawn.rs:28:35
   |
28 |         Handle(&'a smol::Executor<'a>),
   |                                   ^^ unexpected lifetime argument
```
I'll bump the minimum smol version too.

**Comment by Restioson** [comment]
I've released beta 6 with `with-smol-1` renamed to `with-smol-1_1` to reflect the change in minimal version.
