### ISSUE TITLE
Update to tokio 0.3

### ISSUE THREAD

**Issue by Restioson** [Restioson/xtra#24]
First a `with-tokio-0_3` feature will be added along with the deprecation of `with-tokio-0_2`, and then when 0.6.0 releases `with-tokio-0_2` will probably be removed unless there is significant desire for it.

**Comment by Restioson** [comment]
Since tokio 1.0 is out, xtra should just update to that.

**Comment by koushiro** [comment]
@Restioson When do you plan to release the new version?

**Comment by Restioson** [comment]
> @Restioson When do you plan to release the new version?

I'm going to release 0.5.0-rc1 now and then 0.5.0 proper about two weeks later if no other issues arise.

**Comment by Restioson** [comment]
0.5.0-rc.1 has been released for testing
