### ISSUE TITLE
Rename `Handler` trait to `Handles`

### ISSUE THREAD

**Issue by mneumann** [Restioson/xtra#30]
IMHO this generally reads better. Actor framework `Acteur` is using this notion btw. 

Especially in the `where` clauses, `T: Handles<Msg>` just sounds better IMHO.

Personal taste, so please close if you disagree :).

**Comment by Restioson** [comment]
I'll consider this, but I'm not entirely sold (for instance, to me `Handles<Msg>` scans like the plural of the noun `Handle`). Thanks for the suggestion though! If others who use the library see this, your opinion would be appreciated :)

**Comment by Restioson** [comment]
Closing since there hasn't been any other interest in renaming the trait
