### ISSUE TITLE
Request: PartialEq for MessageChannel

### ISSUE THREAD

**Issue by xkns** [Restioson/xtra#37]
I've been implementing the observer pattern over `MessageChannel`s. Minimal example of what I'm trying to do:
```rust
use xtra::{Message, prelude::MessageChannel};

struct Subject<M: Message> {
    observers: Vec<Box<dyn MessageChannel<M>>>
}

impl<M: Message> Subject<M> {
    pub fn register_observer(&mut self, observer: Box<dyn MessageChannel<M>>) {
        // Add observer if not already present
        if !self.observers.contains(&observer) {
            self.observers.push(observer);
        }
    }
}
```
The problem is that `self.observers.contains(&observer)` does not compile because `MessageChannel` does not implement `PartialEq`.
While not strictly necessary it would be nice to be able to deduplicate the `observers` vector.

I have tried determining if this request i.e. implementing `PartialEq` for `MessageChannel` and in turn for `Address` is unreasonable but I don't have a good enough understanding of the inner workings of `Address`. Feel free to close this issue if it is nonsense.

Thank you very much for your effort and time :)

**Comment by Restioson** [comment]
Hi :)

Just to double check, PartialEq would check if the two addresses pointed to the same actor?

**Comment by xkns** [comment]
Yes, that way each registered observing `Actor` would only be present once in the `observers` vector.

And the `notify` method (as per observer pattern; it's missing in my example above) would notify each `Actor` just once.

**Comment by Restioson** [comment]
This seems like a useful implementation - I will get to it when I can

**Comment by Restioson** [comment]
Just wanted to update you - I've thought of a nice solution I think but I'm away for a week and a few days so I will implement it then. Apologies!

**Comment by xkns** [comment]
Thank you very much. I'll have a go at trying it this week and will update you then :)

**Comment by Restioson** [comment]
Alright, no problem :)
