### ISSUE TITLE
xtra and backpressure / load shedding

### ISSUE THREAD

**Issue by vi** [Restioson/xtra#38]
Which channel type is used for sending messages to actors: bounded or unbounded?

If the former, how deadlocks are handled? If the latter, how to do backpressure or load shedding?

> If the actor’s mailbox is full, it will block.

So it looks like bounded channels. What size is the buffer? Can it be switched to unbounded? Shall there be a method like `xtra::address::Address::inflight_messages` to help load shedding and prioritisation?

**Comment by vi** [comment]
Looks like it uses `flume` for channels. Maybe `flume::Sender::len` and `flume::Sender::capacity` should be exposed?

**Comment by Restioson** [comment]
> Which channel type is used for sending messages to actors: bounded or unbounded?

See the `create` method on the `Actor` trait:

> `fn create(self, message_cap: Option<usize>) -> ActorManager<Self>`
> Returns the actor’s address and manager in a ready-to-start state, given the cap for the actor’s mailbox. If None is passed, it will be of unbounded size. To spawn the actor, the ActorManager::spawn must be called, or the ActorManager::run method must be called and the future it returns spawned onto an executor.

The Option argument here is the mailbox size. If it is passed as `None`, unbounded channels are used. If it is passed as `Some`, bounded channels are used.

> If the former, how deadlocks are handled? If the latter, how to do backpressure or load shedding?

I'm unsure what you mean. Could you be more specific?

> Which channel type is used for sending messages to actors: bounded or unbounded?

See the `create` method on the `Actor` trait:

> `fn create(self, message_cap: Option<usize>) -> ActorManager<Self>`
> Returns the actor’s address and manager in a ready-to-start state, given the cap for the actor’s mailbox. If None is passed, it will be of unbounded size. To spawn the actor, the ActorManager::spawn must be called, or the ActorManager::run method must be called and the future it returns spawned onto an executor.

The Option argument here is the mailbox size. If it is passed as `None`, unbounded channels are used. If it is passed as `Some`, bounded channels are used.

> If the former, how deadlocks are handled? If the latter, how to do backpressure or load shedding?

I'm unsure what you mean. Could you be more specific?

>  If the actor’s mailbox is full, it will block.

Only `do_send` will block, as it is a completely synchronous method. Other methods of sending which are `async` will not block but rather `await` more space in the mailbox of the actor.

**Comment by vi** [comment]
OK thanks for the answer; I looked through the docs, but failed to notice `message_cap` somehow.

Shall additional methods of `flume::Sender` (like `is_empty`, `is_full`, `len` and `capacity`) be exposed from `Address` when needed for fine tuning something? Or does `xtra` want to reserve the right to use another underlying channel where counting messages may be problematic?

**Comment by Restioson** [comment]
For now it would be best if `flume` types are put behind a facade, I think, for stability reasons. However, those are reasonable methods to have exposed by an interface in `xtra`, delegating to the `flume` channel. Which methods specifically would you have a usecase for?

**Comment by vi** [comment]
> Which methods specifically would you have a usecase for?

`len` or `capacity` (with a known buffer size they are sort of equivalent, but `len` is more generic, as it works for unbounded channels).

It allows to fine tune reaction to congestion. For example, you want your want most of your channels to be unbounded (to avoid deadlocks) and internal communications between agents (an implementation detail) is not subject to channel capacity pressure. But external requests check `len()` and start rejecting or delaying requests e.g. starting from 50 pending messages and reject even important requests starting from 100 pending messages. This may be useful for tricky schemes for implementing backpressure for short amount of time, but load shedding if congestion is not temporary, also for making different requests fail at different moments as congestion progresses (e.g. having privileged requests that go though even when common requests get blocked).

Obviously, it is possible to just use multiple channels (i.e. bounded channel for common requests + bounded channel for high-priority requests + unbounded channel as internal implementation detail), but just checking `len()` can make things easier and allow implementation without redesigning things and without additional channels.

**Comment by vi** [comment]
I was trying to use xtra though [spaad](https://crates.io/crates/spaad), but missing crates.io publication for Tokio 1 made me abandon the idea - it only worked when both xtra and spaad were specified as Git dependencies. I posted the issue to find spaad+xtra more useful in future if/when I need channelized `async fn`s.

---

Can `capacity()` be added alongside with `len()`? Otherwise either numbers would be hard coded or value specified as `message_cap` would need to be carried everywhere alongside `Address` to be able to do e.g. "if queue is filled over 50% then drop non-priority requests".

**Comment by Restioson** [comment]
> I was trying to use xtra though spaad, but missing crates.io publication for Tokio 1 made me abandon the idea - it only worked when both xtra and spaad were specified as Git dependencies. I posted the issue to find spaad+xtra more useful in future if/when I need channelized async fns.

Shoot, sorry. I forgot to cut a release for spaad. I will cut a release after I add the capacity method like you said. Any other comments?

**Comment by vi** [comment]
> Any other comments?

No as of now. Maybe they will appear when I'll need it next time - if I find a way how to both use Spaad and also be able to fine tune details on Xtra level.

**Comment by Restioson** [comment]
`fn capacity` has been added

**Comment by vi** [comment]
Thanks. Maybe I'll try to `spaad`ify that service if/when I get back to it.

Looks like the issue can be closed after 0.6.0 release - other questions/problems can be handled using separate ones.

> Which channel type is used for sending messages to actors: bounded or unbounded?

Both, choosable by user.

> If the former, how deadlocks are handled?

User should be wary of deadlocks if he bound channel type is chosen, it's not xtra's concern.

> If the latter, how to do backpressure or load shedding?

`len` and `capacity` methods may be used to prevent infinite growth.
