### ISSUE TITLE
Have `xtra` detect deadlocks

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#49]
It would be nice if `xtra` could detect deadlocks where two actors use `.send` to invoke each other from their handlers. Perhaps we can implement some form of "delayed" log message that triggers after a handler has been processing for longer than, say, 5 seconds? If the message itself is also logged, that would help a lot in finding these kind of bugs!

**Comment by Restioson** [comment]
I'm unfamiliar with the techniques used in deadlock detection, but I know parking_lot has experimental deadlock detection. So, if someone else has an implementation strategy, I'd be happy to look at merging a PR.

**Comment by thomaseizinger** [comment]
Are you interested in something like this: https://github.com/comit-network/xtra/commit/15fdd524f2ed3ac94acfc92e21d5f285a485c23d?

**Comment by Restioson** [comment]
Essentially, rather than true deadlock detection, logging if one message has been handled for a long time?

**Comment by thomaseizinger** [comment]
> Essentially, rather than true deadlock detection, logging if one message has been handled for a long time?

Correct. The inspiration came from `cargo test`, which outputs a log if a test takes longer than 60 seconds.

**Comment by thomaseizinger** [comment]
I think so too yeah.

Let's close this in favour of pushing for a more modular design!
