### ISSUE TITLE
Allow actors to return a value from `stopped`

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#53]
This value could be propagated up from `Context::run` and would make it a lot easier to use xtra's actor for tasks that are meant to complete after a while. The result of the task would be the return value from `stopped`.

Thoughts?

**Comment by Restioson** [comment]
This makes sense to me

**Comment by Restioson** [comment]
I can look at this come early Feb, since until then I will be away without reception. It shouldn't be a too difficult change to make though. I do wonder if it'd be breaking or not however.

**Comment by thomaseizinger** [comment]
> I can look at this come early Feb, since until then I will be away without reception. It shouldn't be a too difficult change to make though. I do wonder if it'd be breaking or not however. 

I may beat you to it with a PR then!

Will also see if it can be done non-breaking.

**Comment by Restioson** [comment]
Cool! I think at minimum it will require an associated type:

```rust
trait Actor {
    type StoppedResult = ();
    fn stopped(self) -> Self::StoppedResult;
}
```

I'm unsure if assoc type defaults are stable though.

**Comment by thomaseizinger** [comment]
> I'm unsure if assoc type defaults are stable though.

They are not unfortunately so this will be a breaking change.

**Comment by thomaseizinger** [comment]
Done in #59.
