### ISSUE TITLE
Discoverability for MessageChannel (recipients)

### ISSUE THREAD

**Issue by zesterer** [Restioson/xtra#68]
Actix has support for [`Recipient`](https://actix.rs/actix/actix/prelude/struct.Recipient.html), an alternative to `Address` where the actor type is hidden, leaving only the message itself. This is extremely useful for building large APIs across multiple crates where being able to name actors causes dependency cycles.

How feasible would it be for `xtra` to support this?

**Comment by Restioson** [comment]
Xtra supports this through the [MessageChannel trait](https://docs.rs/xtra/latest/xtra/message_channel/trait.MessageChannel.html). Unlike actix's Recipient though, it's a trait intended to be used as a trait object, so you need to `Box<dyn MessageChannel<M>>` in most cases (though `&dyn MessageChannel<M>` and others can sometimes be helpful).

**Comment by zesterer** [comment]
I think this broadly satisfies this use-case, although it would be nice if this feature were a little more first-class, even if only through a new-type and a method on `Address`.

**Comment by Restioson** [comment]
The reason I decided to make it simply a trait was that then the choice around whether to heap allocate it with Box or & is very apparent, whereas if it were a newtype over the Box, the user might assume that this is the only way to have a message channel. However, more discoverability might be in order. As far as a newtype goes, I would be inclined to make a type alias since I'm not sure a newtype would allow anything more than just `type Recipient<M> = Box<dyn MessageChannel<M>>`. Let me know if there's something else that it could have for quality of life. What would the method on address look like - create a boxed message channel?

**Comment by Restioson** [comment]
> is there an architectural reason that message channels can't be fundamentally parameterised by the message they carry instead of the actor they send to

When you say "message channel" in this context, do you mean the MPSC channel itself?

**Comment by zesterer** [comment]
I'm intrigued by the fact that [`MessageEnvelope`](https://github.com/Restioson/xtra/blob/master/src/envelope.rs#L16-L47) is tied to the receiving actor rather than simply being generic over the message type. This seems like it inherently entangles the sending of messages with the type of their receiver, which seems like the cause of the need to do dynamic dispatch when type erasure is desired.

**Comment by Restioson** [comment]
> I'm intrigued by the fact that [MessageEnvelope](https://github.com/Restioson/xtra/blob/master/src/envelope.rs#L16-L47) is tied to the receiving actor rather than simply being generic over the message type

The way that this currently works is that [`MessageEnvelope::handle`](https://github.com/Restioson/xtra/blob/master/src/envelope.rs#L82) invokes the actor's `Handler<M>`. It cannot do this if it doesn't know the type of `A` at this point. I suppose another method could be possible by rather erasing the actor and taking it as `&dyn Handler<M>`, but I'm just throwing out ideas and haven't looked into this at all so it might be a nonstarter 😅 

This being said, it seems that actix also uses dynamic dispatch internally, though maybe for a different reason: https://docs.rs/actix/latest/src/actix/address/mod.rs.html#253

**Comment by zesterer** [comment]
Thanks for the information. I've suggested this crate as resolution to actix's *many* API footguns at work, and have had a positive response so far. I don't want to unduly place excess load on you as a maintainer, but would you be happy for me to potentially open some PRs to improve aspects of the API perhaps in a month or two if we decide to make the move?

**Comment by Restioson** [comment]
Sure! Keep in mind that there has been a lot of movement from the latest release up until now, so you might want to peruse those first. @thomaseizinger has been doing a lot of very nice work 😄 Thank you for that, by the way!

**Comment by thomaseizinger** [comment]
On that note, I'd like to point at some code that we have written to go with xtra:

- Proc-macro for easier definition of handlers: https://github.com/comit-network/xtra-productivity

Lacks documentation (and a release) but essentially, you put this macro on an `impl MyActor` block and every fn becomes a `Handler` implementation. This will be easier now that we dropped the `Message` trait.

- A crate with some extensions like a supervisor: https://github.com/itchysats/itchysats/tree/master/xtras/src

- We also clippy-ban some of the public API in our codebase: https://github.com/itchysats/itchysats/blob/master/clippy.toml. I have [planned](https://github.com/itchysats/itchysats/issues/1469) to upstream some of this in the form of a more unified `send` API on `Address` but haven't gotten around to it yet.

- Last but not least, we actually run a fork of xtra which some more, not yet upstreamed stuff like `prometheus` metrics: https://github.com/comit-network/xtra/pull/2

cc @klochowicz Perhaps some efforts can be combined here.

**Comment by Restioson** [comment]
I've just renamed this to repurpose this as a discoverability issue for MessageChannel - hope this is ok!

**Comment by Restioson** [comment]
I was just thinking that if Recipient is the terminology generally used, then maybe MesaageChannel can just be renamed to Recipient?
